// Code generated by github.com/gtdavis25/aoc generate. DO NOT EDIT.
package main

import (
	"github.com/gtdavis25/aoc/solver"

	year2024day01 "github.com/gtdavis25/aoc/2024/day01"
	year2024day02 "github.com/gtdavis25/aoc/2024/day02"
	year2024day03 "github.com/gtdavis25/aoc/2024/day03"
	year2024day04 "github.com/gtdavis25/aoc/2024/day04"
	year2024day05 "github.com/gtdavis25/aoc/2024/day05"
	year2024day06 "github.com/gtdavis25/aoc/2024/day06"
	year2024day07 "github.com/gtdavis25/aoc/2024/day07"
	year2024day08 "github.com/gtdavis25/aoc/2024/day08"
	year2024day09 "github.com/gtdavis25/aoc/2024/day09"
	year2024day10 "github.com/gtdavis25/aoc/2024/day10"
	year2024day11 "github.com/gtdavis25/aoc/2024/day11"
	year2024day12 "github.com/gtdavis25/aoc/2024/day12"
)

type SolverFactory func(solver.Params) solver.Interface

var Solvers = map[int]map[int]SolverFactory{
	2024: {
		1: func(params solver.Params) solver.Interface {
			return year2024day01.NewSolver(params)
		},
		2: func(params solver.Params) solver.Interface {
			return year2024day02.NewSolver(params)
		},
		3: func(params solver.Params) solver.Interface {
			return year2024day03.NewSolver(params)
		},
		4: func(params solver.Params) solver.Interface {
			return year2024day04.NewSolver(params)
		},
		5: func(params solver.Params) solver.Interface {
			return year2024day05.NewSolver(params)
		},
		6: func(params solver.Params) solver.Interface {
			return year2024day06.NewSolver(params)
		},
		7: func(params solver.Params) solver.Interface {
			return year2024day07.NewSolver(params)
		},
		8: func(params solver.Params) solver.Interface {
			return year2024day08.NewSolver(params)
		},
		9: func(params solver.Params) solver.Interface {
			return year2024day09.NewSolver(params)
		},
		10: func(params solver.Params) solver.Interface {
			return year2024day10.NewSolver(params)
		},
		11: func(params solver.Params) solver.Interface {
			return year2024day11.NewSolver(params)
		},
		12: func(params solver.Params) solver.Interface {
			return year2024day12.NewSolver(params)
		},
	},
}

func GetSolver(year, day int, params solver.Params) solver.Interface {
	if _, ok := Solvers[year]; !ok {
		return nil
	}

	if _, ok := Solvers[year][day]; !ok {
		return nil
	}

	return Solvers[year][day](params)
}
